### ISSUE TITLE
Better IIFA_GUI_Header_Dropdown

### ISSUE THREAD

**Issue by manavortex** [manavortex/InventoryInsight#32]
N00BxV1 asks:

> First of all thank you so much for IIfA, I absolutely love this addon!
> 
> I was just wondering if you would consider making the ZO_ComboBox control 'IIFA_GUI_Header_Dropdown' some type of scrollable control like a ZO_StatsDropdownRow or ZO_ScrollableComboBox?
> 
> I'm asking because when I open this control to select a source, the dropdown list is almost the size of my entire screen's height, since the combobox does not contain a scroll and all items in the dropdown are shown at once.
> 
> I have 15 characters, about 10 homes, and plus the other All, Banks, Storage, etc listings being shown simultaneously. I'm not sure if this dropdown list with all these contents would fit on the screen if anymore items like more homes/etc were added.
> 
> I realize this is not of great importance and would require time to do, it's just a little request that I think would make the source dropdown look a lot nicer.

Thanks for your time!

**Comment by AssemblerManiac** [comment]
v3.17 has a scrollable listbox, release coming soon

**Comment by AssemblerManiac** [comment]
released in 3.17
