### ISSUE TITLE
Duplicate furniture entries, bound/crown store property not considered

### ISSUE THREAD

**Issue by manavortex** [manavortex/InventoryInsight#4]
If I have an item twice, but one is from crown store and the other isn't.
Two different entries will be generated (correct), but the mouseover tooltip shows the not-bound version twice (incorrect)

**Comment by AssemblerManiac** [comment]
They are the identical item, regardless of whether or not one is from crown store or not. Pretty sure those items are stored by item number, not by full link, so it has no way to separate crown/non-crown status.
