### ISSUE TITLE
item deletion/destruction tracking

### ISSUE THREAD

**Issue by AssemblerManiac** [manavortex/InventoryInsight#5]
When an item is destroyed/deleted from a bag, there's no link in the slot update event.
We need Bag/Slot tracking code that can go find out what it WAS so it can handle the removal.
MakeBSI already stubbed in (creates a Bag/Slot index at char activation). Code to process empty slot update events needs adding.

**Comment by manavortex** [comment]
Fixed in 7dfdfd650005256adbc1f904429300e2ea02cf39
