### ISSUE TITLE
Enable withdrawal via IIfA right click menu

### ISSUE THREAD

**Issue by manavortex** [manavortex/InventoryInsight#52]
LePrau: mana, when will you implement a feature to get an item directl through ii? so
 when I want to retrieve item X which is stored in my housing chest 5, it'll warp
 me there automagically, open the chest, get the item, and warp me back where I
 was?

We could enable withdrawal via right click menu if the user can withdraw from another bag, since we're holding bag and slot ID. Seems trivial.

**Comment by AssemblerManiac** [comment]
Sorry LePrau, this is way beyond "Inventory Insight" which is designed to allow you to see what you have in diff places.
Additionally, if an item exists in 4 diff places, how do you right-click and know you're which one you'll get?
