### ISSUE TITLE
Create data handler

### ISSUE THREAD

**Issue by manavortex** [manavortex/InventoryInsight#6]
create an optional dependency for IIfA, like the FurC data exporter, that holds a list of account names and after IIfA load merges the saved variable data into the database:

`-- iterate over display names    `
`ZO_SavedVars:New(savedVariableTable, version, namespace, defaults, profile, displayName, characterName, characterId, characterKeyType)`

**Comment by AssemblerManiac** [comment]
Since IIfA auto removes orphaned items, this basically won't work. They'll all be merged in, but without a proper owner (char id, or one of the other locs (bank, guild, chest, house), they'll just get deleted in the next cleanup pass.

**Comment by AssemblerManiac** [comment]
Can't see any benefit to this. Closed.
