### ISSUE TITLE
show: FCO itemsaver icons

### ISSUE THREAD

**Issue by Onigar** [manavortex/InventoryInsight#61]
After I enabled show FCO itemsaver icons then sometimes after zoning the FCO locks were no longer there. when I disabled this setting all was working correctly again for FCO itemsaver. 

relogging corrected this issue for a while

Its not a prob for me now as I know not to use it.

**Comment by AssemblerManiac** [comment]
Can you describe the fail case a bit better on FCOIS and IIfA? Is something turning off the FCOIS locks completely (items are no longer tagged at all), or are the locks no longer visible in IIfA, FCOIS or both?

**Comment by Onigar** [comment]
More info:
when this occurred I could see items in the char bag that were marked locked alongside items that are not locked. The filter "green star" is selected.

When I click on one of these items i get the option to unlock it so it is still locked as far as FCOIS is concerned but the icon is not displayed and somehow this allows it to be displayed in the green star filter.

All locked items were affected.

after a relog all the locked items again have their icons and are filtered correctly.

I was moving zones over about 2 hours just guild store shopping or picking up surveys.

It happened at least 3 times but how often it occurred I cannot say as it was only noticeable when I looked in my char bag which was not so often.

After un-setting this option in IIFA I have done 3 further days of long shopping with no issue regarding locked items losing the icon.

Hope this helps, if you want anything more then let me know and I will try to see what else I can remember or even repeat the prob to get you more data.

**Comment by Onigar** [comment]
additional: When this happened I did not look to see if the locks were still there or not in the IIFA window so cant comment on this

**Comment by Baertram** [comment]
I don't get it sorry.
Could you maybe describe 1 example with the info which panel (standard game Inventory, or IIfA window) shows/did not show what marker icon anymore?

With "the green star" you mean the 4 FCOItemSaver filter buttons at the base game inventory bottom line? Which button did you press so it was green? The most left one?
What marker icon are we talking about? The normal "lock" icon (which is filtered via the most left filter button)?

Maybe you can provide screenshots of what you mean as well?

Many thanks for your help but I cannot understand how to reproduce or test this so far :-(

**Comment by Onigar** [comment]
![no lock icon_li](https://user-images.githubusercontent.com/41226484/46243984-f5906280-c3d9-11e8-907a-95b8823cf332.jpg)

My earlier comment pointing to the IIFA setting as a cause is likely a red herring as this occurred after zoning when that setting was off.

I did discover that by selecting to show all items in the bag and by cycling the green star filter(1) through red and yellow then back to green then the lock icons were again displayed against the items that are locked.

you can see at (3) even though there is no lock icon FCOIS recognises the item is locked
