### ISSUE TITLE
Search not re-applied on change of "what to show" dropdown box

### ISSUE THREAD

**Issue by Baertram** [manavortex/InventoryInsight#65]
IIfA still got this bug with the search box, if you switch to another bag from the dropdown box at the top.

How to reproduce:
1. Open IIfA, having current char bag + bank active as default dropdown entry + search box focus automatically set in settings
2. Enter search criteria into search box -> show found items (e.g. in bank + guild bank)
3. Change the dropdown box at the top to "All" -> Should still show the searched and found entries from before.

But it is not showing anything anymore.
You can press the return key in the search box and it still does not show anything.
As I remove a character, or add one, into the search box the entries will be shown again finally.

Seems as if the search is not re-applied after changing the dropdown box at the top

**Comment by AssemblerManiac** [comment]
I can't duplicate this. 
I've tried with/without default dropdown entry, with/without auto-focus on search area. Whenever I change the top dropdown, it re-selects all the item properly.

The functions IIfA:SetInventoryListFilter(choiceText) and IIfA:RefreshInventoryScroll() are both called on every dropdown item change.

**Comment by Baertram** [comment]
Well this must be an issue with other addons or the German client then?
I'll test IIfA without other addons again and write a detailed "how to rebuild" here.

**Comment by Baertram** [comment]
These are my settings of IIfA as tht bug happens:

[[[SavedVars]]]
Use global settings Yes
Debugging No

[Guild Bank Options]
GB Data collection Yes
Collect data for Guild1 Yes
Collect data for Guild2 Yes
Collect data for Guild3 No
Collect data for Guild4 Yes
Collect data for Guild5 No

[Houses]
Collect furniture imn houses No

[Pack/Use/Size Highlites]
Used space warning 85
Used space warning color Orange (default?)
Used space alert 95
Used space alert color Yellow (standard?)
Used space Full color Red (standard?)

[Tooltips]
Show IIfA tooltips Always
Show info in seperate frame No
Show style info No
Tooltip owner Color ... All standard
Tooltips Font ZoFontGame
Tooltip Font Size 16

Item Count on Right Yes
Show item stats No
Default Inventory Frame View    Bank and current character
Focus search box Yes
Text filter considers set name as well Yes
Text filter only searches set names No

 [Major scene toggles]
All off!

[Other Addons]
FCOItemSaver
-> Show marker icons  Yes


------TESTS---------------
Logged in, several addons enabled. Opened IIfA frame once. Did no search.
Went to AddonManager -> Only enabled Inventory Insight and did a reloadui.
IIfA frame was reopened autoamtically as it was shown before the AddonManager was opened.

**With only IIfA enabled:**
IIfA frame shows the standard view: Bank and current character.
Focus the IIfA frame and click into the search box.
Typing "band" and all items with "band" in the name will be filtered and shown.  - > OK
Switching the shown view from "Bank and current character" to "All".
All other items containing "band" are shown properly. -> OK

**Logout.** 
Login again, same char. Only IIfA enabled.
Using keybind to show IIfA frame.
Search box got automatically the focus due to the settings! (**difference to reloadui after addons were disabled in the inventory manager during the test before**).
Typing "band" and all items with "band" in the name will be filtered and shown.  - > OK
Switching the shown view from "Bank and current character" to "All".
All other items containing "band" are shown properly. -> OK

So this seems to work properly.
Trying with other addons enabled then again in the future.

**Comment by Baertram** [comment]
After testing with other addons enabled I cannot even reproduce it for now...
But it was there, several times since months now!
It must be some constellatin during gameplay then, after zone change/reloadui/whatever :-(

**Comment by Baertram** [comment]
Just got the error again.

Logged in with a new char, opened inventory, changed to junk tab, searched stuff there and found a jewelry ring.
Pressed shortkey to open IIfA UI. It was shown the "Current character and bank" entry and the search edit box got the focus automatically (settings of IIfA).
Searched for the ring's name "Dremora" and found it on my current character only.
Changed the search edit entry text from "Draemora" to "Ebenerz" but did not press the RETURN key.
Changed the IIfA dropdown box to "All" and the search got not re-applied automatically.
-> I need to change the search edit entry again so the search will be applied.

Did a reloadui and tried to rebuild the bug again:
Works!

Active addons (76) as this bug happens were:
                        ["GreymindQuickSlotBar"] = "Greymind|r Quick Slot Bar",
                        ["DolgubonsLazyWritCreator"] = "Dolgubon's Lazy Writ Creator v2.5.15.3",
                        ["FCOCraftFilter"] = "FCO CraftFilter|r",
                        ["AF_FCOSetsFilters"] = "Advanced Filters - Sets Filter",
                        ["LibFoodDrinkBuff"] = "LibFoodDrinkBuff",
                        ["LibPotionBuff"] = "LibPotionBuff",
                        ["LibFilters-2.0"] = "LibFilters-2.0",
                        ["LibStub"] = "LibStub",
                        ["AF_ResearchAssistantFilters"] = "Advanced Filters - Research Assistant Filters",
                        ["FCOGuildInfo"] = "FCO GuildInfo|r",
                        ["pChat"] = "pChat",
                        ["LibFeedback"] = "LibFeedback",
                        ["LibLoadedAddons"] = "LibLoadedAddons",
                        ["IIfA"] = "Inventory Insight",
                        ["has2lam"] = "Harven's AS to LAM adapter",
                        ["AlphaGear"] = "AlphaGear 2|r v6.4.1 beta2",
                        ["LibAlchemyStation"] = "LibAlchemyStation",
                        ["Zgoo"] = "Zgoo",
                        ["VotansAchievementFavorites"] = "Votan's Achievement Favorites",
                        ["LibMediaProvider-1.0"] = "LibMediaProvider-1.0",
                        ["VotansCraftingQuickAccess"] = "Votan's Crafting Quick Access",
                        ["CraftBagExtended"] = "Craft Bag Extended",
                        ["FCOLockpicker"] = "FCO Lockpicker|r",
                        ["Recharge"] = "Auto Recharge",
                        ["AF_FCOStolenFilters"] = "Advanced Filters - Stolen items filter",
                        ["AF_FCOBoundItemsFilter"] = "Advanced Filters - Bound items filter",
                        ["BeamMeUp"] = "BeamMeUp|r - Teleporter",
                        ["LibSavedVars"] = "LibSavedVars",
                        ["PerfectPixel"] = "PerfectPixel",
                        ["FCOChatTabBrain"] = "FCO Chat Tab Brain|r",
                        ["LibAddonMenu-2.0"] = "LibAddonMenu-2.0",
                        ["AF_RecipeFilters"] = "Advanced Filters - Recipe Filters",
                        ["LibDialog"] = "LibDialog",
                        ["AF_FCOConsumablesLevelFilters"] = "Advanced Filters - Consumables Level Filters",
                        ["ActionDurationReminder"] = "Action Duration Reminder",
                        ["TamrielTradeCentre"] = "Tamriel Trade Centre",
                        ["FCOUltimateReminder"] = "FCO UltimateReminder|r",
                        ["AssistRapidRiding"] = "Assist Rapid Riding",
                        ["PotionMaker"] = "Potion Maker (for Alchemy Crafting)",
                        ["FCOUltimateSound"] = "FCO Ultimate Sound|r",
                        ["VotansSettingsMenu"] = "Votan's Settings Menu",
                        ["LibHarvensAddonSettings"] = "Harven's Addon Settings",
                        ["AF_FCOItemSaverFilters"] = "Advanced Filters - FCO Item Saver Filters",
                        ["VotanSearchBox"] = "Votan's Search Box",
                        ["LibAsync"] = "LibAsync",
                        ["VotansMiniMap"] = "Votan's Minimap",
                        ["AF_FCORawMaterialFilters"] = "Advanced Filters - RAW materials filter",
                        ["AF_FCOItemTraitType"] = "Advanced Filters - Item trait type",
                        ["AF_FCOMaterialLevelFilters"] = "Advanced Filters - Material Level Filters",
                        ["AF_FCOMiscellaneousLevelFilters"] = "Advanced Filters - Miscellaneous Level Filters",
                        ["FCORepair"] = "FCO Repair|r",
                        ["ResearchAssistant"] = "Research Assistant",
                        ["Postmaster"] = "Postmaster",
                        ["DoItAll"] = "DoItAll",
                        ["MapPins"] = "Map Pins|r",
                        ["AdvancedFilters"] = "Advanced Filters",
                        ["LibZone"] = "LibZone",
                        ["FCONotes"] = "FCO Notes|r",
                        ["FCOChangeStuff"] = "FCO ChangeStuff|r",
                        ["FCOMounty"] = "FCO Mounty|r",
                        ["WishList"] = "Wish List",
                        ["AF_JewelryDeconStatusFilters"] = "Advanced Filters - Jewelry Deconstructable Status Filters",
                        ["FCOGuildBankQuickSelect"] = "FCO GuildBankQuickSelect|r",
                        ["CraftingMaterialLevelDisplay"] = "Crafting Material Level Display",
                        ["AF_FCOQualityLevelFilters"] = "Advanced Filters - Quality Level Filters",
                        ["SousChef"] = "Sous Chef by Wobin, CrazyDutchGuy & KatKat42",
                        ["AddonSelector"] = "Addon Selector",
                        ["AF_DuplicateFilter"] = "Advanced Filters - Duplicate items filter",
                        ["LibCustomMenu"] = "LibCustomMenu",
                        ["AF_FCOUniqueItems"] = "Advanced Filters - Unique items filter",
                        ["FCOStarveStop"] = "FCO StarveStop|r",
                        ["LibMainMenu-2.0"] = "LibMainMenu-2.0",
                        ["AF_CraftingMaterialLevelFilters"] = "Advanced Filters - Crafting Material Level Filters",
                        ["FCOItemSaver"] = "FCO ItemSaver|r",
                        ["BugEater"] = "BugEater",
                        ["DailyProvisioning"] = "Daily Provisioning",
                        ["AF_SousChefFilters"] = "Advanced Filters - Sous Chef Filters",


![search_box_bug_1](https://user-images.githubusercontent.com/1195208/51088760-1059cd80-1764-11e9-9563-cd7d43c76da3.JPG)
![search_box_bug_1 5](https://user-images.githubusercontent.com/1195208/51088767-28315180-1764-11e9-9dac-c59b5f93ea7a.JPG)
![search_box_bug_2](https://user-images.githubusercontent.com/1195208/51088754-fa4c0d00-1763-11e9-920c-17d58c91c620.JPG)
![search_box_bug_3](https://user-images.githubusercontent.com/1195208/51088755-fae4a380-1763-11e9-8d09-74b4fff354a6.JPG)


I did test if the bug happens with all other addons disabled as well.
It does.

**Comment by AssemblerManiac** [comment]
Solved in 3.23

**Comment by Sharlikran** [comment]
It was resolved in https://github.com/manavortex/InventoryInsight/commit/e017265c998d665aba5dfd034b47217cff7f12fb
