### ISSUE TITLE
Guild bank tracking resets itself

### ISSUE THREAD

**Issue by manavortex** [manavortex/InventoryInsight#66]
Ekoe: 
> I have found all the options for untracking guilds you don't wish to see, and deleted the data from specific guilds.  Unfortunately, no matter how many time I tick to ONLY track on guild bank, and delete the collected datat from the other two,  that I don't wish tracked....  This add on resets all on it's own, and the date collection on the other guild banks gets turned back to "ON" mode,
> 
> Any way of stopping it from resetting to the ON position?

https://www.esoui.com/downloads/fileinfo.php?id=731#comments

**Comment by AssemblerManiac** [comment]
This has been solved
