### ISSUE TITLE
Einlagern von Char zu Bank

### ISSUE THREAD

**Issue by Scootworks** [manavortex/InventoryInsight#9]
`
user:/AddOns/IIfA/IIfAEvents.lua:29: attempt to index a nil value
stack traceback:
    user:/AddOns/IIfA/IIfAEvents.lua:29: in function 'IIfA:InventorySlotUpdate'
    user:/AddOns/IIfA/IIfAEvents.lua:44: in function 'IIfA_InventorySlotUpdate'
`

**Comment by AssemblerManiac** [comment]
as far as we know, this is solved
